services:
    # ud-parsers (812X)
    spacy:
        image: instituutnederlandsetaal/taggers-dockerized-spacy:${VERSION}
        restart: unless-stopped
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8120:8080
    stanza:
        image: instituutnederlandsetaal/taggers-dockerized-stanza:${VERSION}
        restart: unless-stopped
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8121:8080

networks:
    default:
        name: taggers-network
        driver: bridge # external applications can attach to this network to access the taggers 
