services:
    # ud-parsers (812X)
    spacy-gpu:
        image: instituutnederlandsetaal/taggers-dockerized-spacy:${VERSION}
        restart: unless-stopped
        environment:
            - USE_GPU=1
            - NUM_WORKERS=6
        ports:
            - 8120:8080
        deploy:
            resources:
                limits:
                    memory: 24G
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ gpu ]

    stanza:
        image: instituutnederlandsetaal/taggers-dockerized-stanza:${VERSION}
        restart: unless-stopped
        ports:
            - 8121:8080
        deploy:
            resources:
                limits:
                    memory: 24G
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ gpu ]


networks:
    default:
        name: taggers-network
        driver: bridge # external applications can attach to this network to access the taggers 
