name: Prod images to Docker

on:
  push:
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  prod-images-to-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push 
        run: ./buildandpushall.sh
        env:
          VERSION: latest
